apiVersion: v1
name: node-busybox
home: unimednatal.com.br
version: v1.1.0
appVersion: v1.1.0
icon: https://mir-s3-cdn-cf.behance.net/project_modules/max_3840/21926c49221993.58ae3b9c8bdd5.jpg
description: Aplicação básica em NodeJS mostrando algumas funções do Hello World e o Cookie Parser.
sources:
  - https://github.com/LuksJobs/node-busybox
keywords:
  - nodejs
  - kubernetes
  - express
maintainers:
  - name: Lucas Oliveira Dantas
    email: luksjobs@live.com
    url: https://luks.dev.br