{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "node-busybox.fullname" . }}-clusterrole
  labels:
    app.kubernetes.io/name: {{ include "node-busybox.name" . }}
    helm.sh/chart: {{ include "node-busybox.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
{{- if .Values.podSecurityPolicy.enabled }}
  - apiGroups: [ "extensions" ]
    resourceNames: [ "node-busybox-psp" ]
    resources: [ "podsecuritypolicies" ]
    verbs: [ "use" ]
{{ end }}
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get" ]
  - apiGroups: [ "" ]
    resources: [ "secrets", "configmaps" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "list" ]
  - apiGroups: [ "" ]
    resources: [ "users", "groups", "serviceaccounts" ]
    verbs: [ "impersonate" ]
  {{- end }}