apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.Name }}
  annotations:
    version: {{ .Chart.Version }}
  creationTimestamp: null
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  ports:
    - name: {{ .Chart.Name }}
      port: {{ .Values.service.Port }}
      targetPort: {{ .Values.service.targetPort }}
  externalIPs:
    - 10.10.33.10 #control-plane
    - 10.10.33.17 #worker-prd-01
    - 10.10.33.18 #worker-prd-02
    - 10.10.33.19 #worker-prd-03 
    - 10.10.33.20 #worker-prd-04

  selector:
    app: {{ .Chart.Name }}
status:
  loadBalancer: {}