apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: api-servicos
  name: api-servicos
spec:
  ports:
    - name: "api-servicos"
      port: 5023
      targetPort: 3002
  externalIPs:
    - 10.10.33.10 #rancher-prd-01 (control-plane)
    - 10.10.33.17 #worker-prd-01
    - 10.10.33.18 #worker-prd-02
    - 10.10.33.19 #worker-prd-03
    - 10.10.33.20 #worker-prd-02
   
  selector:
    io.kompose.service: api-servicos
status:
  loadBalancer: {}