apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.Name }}
  annotations:
    version: {{ .Chart.Version }}
  creationTimestamp: null
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  ports:
    - name: {{ .Chart.Name }}
      port: {{ .Values.service.Port }}
      targetPort: {{ .Values.service.targetPort }}
  externalIPs:
    - 192.168.0.162 #control-plane

  selector:
    app: {{ .Chart.Name }}
status:
  loadBalancer: {}